FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["sh", "-c", "python manage.py makemigrations payment_service && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
